version: '3.1'
volumes:
  influxdb:
  grafana:
services:

  influxdb:
    image: influxdb
    restart: always
    container_name: influxdb
    ports:
      - 8886:8086
      - 3300:3000
    volumes:
      - influxdb:/var/lib/influxdb

  grafana:
    image: grafana/grafana
    restart: always
    depends_on:
      - influxdb
    container_name: grafana
    volumes:
      - grafana:/var/lib/grafana
    network_mode: "service:influxdb"
